import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import './globals.css'
import SideBar from '@/components/SideBar'
import SideBarItem from '@/components/SideBarItem'
import Icon from '@/components/Icon'
import Badge from '@/components/Badge'

const urbanistFont = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Content Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={urbanistFont.className}>
        <SideBar
          navItems={<>
            <SideBarItem icon={<Icon icon="media"/>} label="Content" active/>
            </>}
          footerItems={<>

          
            </>}
        >
          {children}
        </SideBar>
      </body>
    </html>
  )
}
